# 项目相关配置 dev配置
devtools:
  restart:
    # 热部署开关
    enabled: true
  redis:
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最小空闲连接
        max-idle: 10
    timeout: 500000
    host: 127.0.0.1
    port: 6379
    password:
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8089
  servlet:
    # 应用的访问路径
    context-path: /

# 日志配置
logging:
  level:
    com.lysoftbas: debug
    org.springframework: WARN



  # PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql




